// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hackhathonTarnow.Context;

namespace hackhathonTarnow.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20190414074816_parkingVehicles")]
    partial class parkingVehicles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("hackhathonTarnow.Models.Parking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<float>("Latitude");

                    b.Property<float>("Longtitude");

                    b.Property<int>("NumberOfFreeCarsPlaces");

                    b.Property<int>("NumberOfFreeCyclesPlaces");

                    b.Property<int>("NumberOfFreeDisabledPlaces");

                    b.Property<int>("NumberOfFreePlaces");

                    b.Property<int>("NumberOfPlaces");

                    b.HasKey("Id");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("hackhathonTarnow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardId");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<int>("PESEL");

                    b.Property<string>("Password");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("hackhathonTarnow.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CarPlate");

                    b.Property<Guid?>("ParkingId");

                    b.Property<Guid?>("UserId");

                    b.Property<string>("VehicleType");

                    b.HasKey("Id");

                    b.HasIndex("ParkingId");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("hackhathonTarnow.Models.Vehicle", b =>
                {
                    b.HasOne("hackhathonTarnow.Models.Parking", "Parking")
                        .WithMany("Vehicles")
                        .HasForeignKey("ParkingId");

                    b.HasOne("hackhathonTarnow.Models.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
